global:
  scrape_interval:     36s

scrape_configs:
  - job_name: "node-exporter"
    static_configs:
    - targets: ["node-exporter:9100"]

  - job_name: "grafana"
    static_configs:
    - targets: ["grafana:3000":]
